services:
  - type: web
    name: keycloak
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: PORT
        value: 8080
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      - key: KC_HOSTNAME
        value: keycloak-for-deploy-1.onrender.com
      - key: KC_PROXY
        value: edge
      - key: KC_CACHE
        value: local
      - key: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
        value: true